import LocalizedStrings from "react-native-localization";
import { SCREEN_TABS } from "../navigators/constants";

export let strings = new LocalizedStrings({
    en: {
        email: "Email",
        password: "Password",
        signInWelcomeText: "Welcome to MoviesReview",
        signUpWelcomeText: "Let's get started",
        authValidEmail: "Please enter valid email!",
        authValidPassword: "Passwords must have atleast 6 charecters",
        newUserText: "New to MoviesReview?",
        signUp: "Sign up now",
        signIn: "Sign In",
        logout: "Logout",
        passwordMatch: "Passwords dont match",
        exsistingUser: "Already have an account?",
        SignGoogle: "Sign in with Google",
        btSignup: "Sign up",
        resetPassword: "Reset Password",
        editProfile: "Edit Profile",
        myProfile: "My Profile",
        fName: "Firstname",
        lName: "Lastname",
        update: "Update",
        newPassword: "New Password",
        currentPassword: "Current Password",
        editPassword: "Edit Password",
        favTitle: "My Stuff",
        noItem: "Browse now, add watch later!",
        video: "videos",
        deleteItem: "Delete Favourites",
        search: "search",
        noResult: "No results found!",
        titleMain: "Recently Added Movies",
        bollywood: "Bollywood Movies",
        welcome: "Welcome",
        post: "Post",
        watchlist: "Watchlist",
        share: "Share",
    },
    it: {
        email: "e-mail",
        password: "parola d'ordine",
        signInWelcomeText: "Benvenuto su MoviesReview",
        signUpWelcomeText: "Iniziamo",
        authValidEmail: "Inserire una email valida, grazie!",
        authValidPassword: "Le password devono avere almeno 6 caratteri",
        newUserText: "Nuovo su MoviesReview?",
        signUp: "Iscriviti ora",
        signIn: "Registrazione",
        logout: "disconnettersi",
        passwordMatch: "Le password non corrispondono",
        exsistingUser: "Hai già un account?",
        SignGoogle: "Accedi con Google",
        btSignup: "Iscriviti",
        resetPassword: "Resetta la password",
        editProfile: "Modifica Profilo",
        myProfile: "Il mio profilo",
        fName: "Nome di battesimo",
        lName: "Cognome",
        update: "aggiornare",
        newPassword: "nuova password",
        currentPassword: "password attuale",
        editPassword: "Modifica password",
        favTitle: "La mia roba",
        noItem: "Sfoglia ora, aggiungi orologio più tardi!",
        video: "video",
        deleteItem: "Elimina Preferiti",
        search: "Ricerca",
        noResult: "Nessun risultato trovato!",
        titleMain: "Film aggiunti di recente",
        bollywood: "Film di Bollywood",
        welcome: "Benvenuta",
        post: "Inviare",
        watchlist: "Lista di controllo",
        share: "Condividere",
    },
});

export const englishConverter = ({ navigation }) => {
    strings.setContent({
        en: {
            email: "Email",
            password: "Password",
            signInWelcomeText: "Welcome to MoviesReview",
            signUpWelcomeText: "Let's get started",
            authValidEmail: "Please enter valid email!",
            authValidPassword: "Passwords must have atleast 6 charecters",
            newUserText: "New to MoviesReview?",
            signUp: "Sign up now",
            signIn: "Sign In",
            logout: "Logout",
            passwordMatch: "Passwords dont match",
            exsistingUser: "Already have an account?",
            SignGoogle: "Sign in with Google",
            btSignup: "Sign up",
            resetPassword: "Reset Password",
            editProfile: "Edit Profile",
            myProfile: "My Profile",
            fName: "Firstname",
            lName: "Lastname",
            update: "Update",
            newPassword: "New Password",
            currentPassword: "Current Password",
            editPassword: "Edit Password",
            favTitle: "My Stuff",
            noItem: "Browse now, add watch later!",
            video: "videos",
            deleteItem: "Delete Favourites",
            search: "search",
            noResult: "No results found!",
            titleMain: "Recently Added Movies",
            bollywood: "Bollywood Movies",
            welcome: "Welcome",
            post: "Post",
            watchlist: "Watchlist",
            share: "Share",
        },
    });
    navigation.navigate(SCREEN_TABS.Signin);
};

export const italianConverter = ({ navigation }) => {
    strings.setContent({
        it: {
            email: "e-mail",
            password: "parola d'ordine",
            signInWelcomeText: "Benvenuto su MoviesReview",
            signUpWelcomeText: "Iniziamo",
            authValidEmail: "Inserire una email valida, grazie!",
            authValidPassword: "Le password devono avere almeno 6 caratteri",
            newUserText: "Nuovo su MoviesReview?",
            signUp: "Iscriviti ora",
            signIn: "Registrazione",
            logout: "disconnettersi",
            passwordMatch: "Le password non corrispondono",
            exsistingUser: "Hai già un account?",
            SignGoogle: "Accedi con Google",
            btSignup: "Iscriviti",
            resetPassword: "Resetta la password",
            editProfile: "Modifica Profilo",
            myProfile: "Il mio profilo",
            fName: "Nome di battesimo",
            lName: "Cognome",
            update: "aggiornare",
            newPassword: "nuova password",
            currentPassword: "password attuale",
            editPassword: "Modifica password",
            favTitle: "La mia roba",
            noItem: "Sfoglia ora, aggiungi orologio più tardi!",
            video: "video",
            deleteItem: "Elimina Preferiti",
            search: "Ricerca",
            noResult: "Nessun risultato trovato!",
            titleMain: "Film aggiunti di recente",
            bollywood: "Film di Bollywood",
            welcome: "Benvenuta",
            post: "Inviare",
            watchlist: "Lista di controllo",
            share: "Condividere",
        },
    });
    navigation.navigate(SCREEN_TABS.Signin);
};
